// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAeRAAnTOgjdY0S9F4BKe95vtPYR8JrM',
    appId: '1:196255449244:web:167acfe7ed7b9d6dfaad59',
    messagingSenderId: '196255449244',
    projectId: 'chat-app-76477',
    authDomain: 'chat-app-76477.firebaseapp.com',
    storageBucket: 'chat-app-76477.appspot.com',
    measurementId: 'G-W7MLHH8GQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpMRgwTX3b78y2B7I-5_b1FzyIIBVsuo',
    appId: '1:196255449244:android:8e2447e5295bb06afaad59',
    messagingSenderId: '196255449244',
    projectId: 'chat-app-76477',
    storageBucket: 'chat-app-76477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSwpjQhukcVgSfbwn67dnoZrARDlYkGE',
    appId: '1:196255449244:ios:e056c597251b2847faad59',
    messagingSenderId: '196255449244',
    projectId: 'chat-app-76477',
    storageBucket: 'chat-app-76477.appspot.com',
    iosClientId: '196255449244-famf7bd0p2l0tc7rhps6i3gqjna4gd5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSwpjQhukcVgSfbwn67dnoZrARDlYkGE',
    appId: '1:196255449244:ios:e056c597251b2847faad59',
    messagingSenderId: '196255449244',
    projectId: 'chat-app-76477',
    storageBucket: 'chat-app-76477.appspot.com',
    iosClientId: '196255449244-famf7bd0p2l0tc7rhps6i3gqjna4gd5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
